# -*- coding: utf-8 -*-
"""
@author:XuMing(xuming624@qq.com)
@description: Path resolution utilities — glob, directory walk, .gitignore support.

Resolves a mix of files, globs, and directories into a flat list of file paths,
with configurable ignore rules and optional .gitignore support via ``pathspec``.
"""
import glob as globmod
import logging
import os
logger = logging.getLogger(__name__)

# Default directories to skip during recursive walk
DEFAULT_IGNORE_DIRS: frozenset[str] = frozenset({
    ".git", ".hg", ".svn",
    "node_modules", "__pycache__", ".venv", "venv", "env",
    "dist", "build", ".tox", ".mypy_cache", ".pytest_cache",
    ".eggs", ".cortex",
})

# Patterns for directory names (matched with fnmatch-style)
_IGNORE_DIR_PATTERNS: frozenset[str] = frozenset({
    "*.egg-info",
})

MAX_DIR_FILES: int = 10_000


def _get_default_extensions() -> set[str]:
    """Return all file extensions supported by the parser registry + SOURCE_TYPE_MAP."""
    from .parsers.registry import ParserRegistry, SOURCE_TYPE_MAP

    exts: set[str] = set()
    exts.update(ParserRegistry.supported_extensions())
    exts.update(SOURCE_TYPE_MAP.keys())
    return exts


def get_allowed_extensions_for_source_types(source_types: list[str]) -> set[str] | None:
    """If *source_types* is non-empty, return the set of extensions belonging
    to those source types.  Return ``None`` when the list is empty (meaning
    "all types allowed").
    """
    if not source_types:
        return None
    from .parsers.registry import SOURCE_TYPE_MAP
    return {ext for ext, st in SOURCE_TYPE_MAP.items() if st in source_types}


def _find_gitignore(start_dir: str) -> str | None:
    """Return ``<start_dir>/.gitignore`` if it exists, else ``None``.

    Only the gitignore at the indexed root is consulted — parent project
    gitignores are intentionally NOT walked into. Otherwise indexing a
    subdirectory of a project (e.g. a dir that the project's own .gitignore
    marks as ignored) would silently filter out every file, contradicting
    the user's explicit intent to index that directory. This also matches
    ``resolve_paths``'s documented behaviour ("honour .gitignore files
    found at the root of walked directories").
    """
    candidate = os.path.join(os.path.abspath(start_dir), ".gitignore")
    return candidate if os.path.isfile(candidate) else None


def _load_gitignore_spec(root: str):
    """Load ``<root>/.gitignore`` as a ``pathspec`` matcher.

    Returns a ``(pathspec.PathSpec, base_dir)`` tuple, or ``(None, root)``
    if the file is not found or ``pathspec`` is not installed.
    """
    gitignore_path = _find_gitignore(root)
    if not gitignore_path:
        return None, root
    import pathspec
    base_dir = os.path.dirname(gitignore_path)
    with open(gitignore_path, "r", encoding="utf-8", errors="replace") as f:
        return pathspec.PathSpec.from_lines("gitwildmatch", f), base_dir


def _should_ignore_dir(dirname: str, ignore_dirs: frozenset[str]) -> bool:
    """Check if a directory name should be ignored."""
    if dirname in ignore_dirs:
        return True
    import fnmatch
    for pat in _IGNORE_DIR_PATTERNS:
        if fnmatch.fnmatch(dirname, pat):
            return True
    return False


def shadow_md_path(source_path: str) -> str:
    """Return the shadow Markdown path for a binary source file.

    ``dir/paper.pdf`` -> ``dir/._paper.pdf.md``
    """
    dirname = os.path.dirname(source_path)
    basename = os.path.basename(source_path)
    return os.path.join(dirname, "._" + basename + ".md")


def _walk_directory(
    directory: str,
    *,
    allowed_extensions: set[str] | None = None,
    ignore_dirs: frozenset[str] = DEFAULT_IGNORE_DIRS,
    respect_gitignore: bool = True,
    max_files: int = MAX_DIR_FILES,
    follow_symlinks: bool = False,
) -> list[str]:
    """Recursively walk *directory* and return matching file paths."""
    directory = os.path.abspath(directory)
    gitignore_spec, gitignore_base = _load_gitignore_spec(directory) if respect_gitignore else (None, directory)

    results: list[str] = []
    for dirpath, dirnames, filenames in os.walk(directory, followlinks=follow_symlinks):
        # Filter out ignored directories (in-place to prevent os.walk descent)
        dirnames[:] = [
            d for d in dirnames
            if not _should_ignore_dir(d, ignore_dirs)
        ]
        dirnames.sort()

        for fname in sorted(filenames):
            # Skip shadow MD files (generated by binary file indexer)
            if fname.startswith("._") and fname.endswith(".md"):
                continue

            # Extension filter
            if allowed_extensions is not None:
                _, ext = os.path.splitext(fname)
                if ext.lower() not in allowed_extensions:
                    continue

            full_path = os.path.join(dirpath, fname)

            # .gitignore filter
            if gitignore_spec is not None:
                rel = os.path.relpath(full_path, gitignore_base)
                if gitignore_spec.match_file(rel):
                    continue

            results.append(full_path)
            if len(results) > max_files:
                raise ValueError(
                    f"Directory '{directory}' contains more than {max_files} matching files. "
                    f"Use a more specific path or increase max_files."
                )

    return results


def resolve_paths(
    patterns: list[str],
    *,
    allowed_extensions: set[str] | None = None,
    ignore_dirs: frozenset[str] = DEFAULT_IGNORE_DIRS,
    respect_gitignore: bool = True,
    max_files: int = MAX_DIR_FILES,
    follow_symlinks: bool = False,
) -> list[str]:
    """Resolve a mix of files, globs, and directories into file paths.

    Resolution rules:
    1. Glob pattern (contains ``*`` or ``?``) -> ``glob.glob(recursive=True)``
    2. Regular file -> include directly
    3. Directory -> recursive walk, filter by *allowed_extensions*,
       skip *ignore_dirs*, optionally respect ``.gitignore``

    Args:
        patterns: list of file paths, glob patterns, or directories.
        allowed_extensions: set of lowercase extensions (e.g. ``{".py", ".md"}``).
            Defaults to all extensions known to the parser registry.
            Only applied to directory walks — explicit files and globs are not filtered.
        ignore_dirs: directory names to skip during recursive walk.
        respect_gitignore: if True and ``pathspec`` is installed, honour
            ``.gitignore`` files found at the root of walked directories.
        max_files: safety cap on total files from a single directory walk.
        follow_symlinks: follow symbolic links during directory walk.

    Returns:
        List of resolved file paths (deduplicated, order-preserved).
    """
    if allowed_extensions is None:
        allowed_extensions = _get_default_extensions()

    # Overlay source_type filter from global config
    from .config import get_config
    source_type_exts = get_allowed_extensions_for_source_types(
        get_config().allowed_source_types
    )
    if source_type_exts is not None:
        allowed_extensions = allowed_extensions & source_type_exts

    resolved: list[str] = []
    seen: set[str] = set()

    def _add(path: str) -> None:
        abspath = os.path.abspath(path)
        if abspath not in seen:
            seen.add(abspath)
            resolved.append(path)

    for p in patterns:
        if "*" in p or "?" in p:
            # Glob pattern
            for match in sorted(globmod.glob(p, recursive=True)):
                if os.path.isfile(match):
                    _add(match)
        elif os.path.isdir(p):
            # Directory → recursive walk
            for fp in _walk_directory(
                p,
                allowed_extensions=allowed_extensions,
                ignore_dirs=ignore_dirs,
                respect_gitignore=respect_gitignore,
                max_files=max_files,
                follow_symlinks=follow_symlinks,
            ):
                _add(fp)
        elif os.path.isfile(p):
            # Regular file
            _add(p)
        else:
            logger.warning("Path not found: %s", p)

    return resolved
